# Site settings
title: kevin的blog    				  	#你博客的标题
SEOTitle: Kevin的博客 | 呃呃呃   	 #显示在浏览器上搜索的时候显示的标题
header-img: /img/!iconbird.png  	#显示在首页的背景图片
email: kevinzhw153@126.com	
description: "my blog"  			 #网站介绍
keyword: "kevin的博客," #关键词
url: "https:/kevinzhw153.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "test"
sidebar-avatar:/img/!bridge.jpg    
# SNS settings
RSS: false
weibo_username:     
zhihu_username:    
github_username:  kevinzhw153
facebook_username: 
jianshu_username:	

# Disqus settings（https://disqus.com/）
disqus_username: kevinzhw153

